### ISSUE TITLE
Add documentation on running BENGAL to README

### ISSUE THREAD

**Issue by munnellg** [dice-group/BENGAL#10]
It is unclear to me how BENGAL should be started from the terminal based on the information currently in the README. I altered the pom on my computer to use the Maven Shade plugin, but it would be better if the README were clearer about the process that you use.

**Comment by DiegoMoussallem** [comment]
Hi @munnellg , first of all, thank you for using BENGAL, we are going to provide it soon.

**Comment by munnellg** [comment]
Cool beans!

It's an interesting project! We've had a lot of problems with identifying evaluation corpora for my particular domain, so the ability to generate pseudo-gold standards is definitely appealing.

**Comment by DiegoMoussallem** [comment]
Nice that you liked it, this idea is also used to check the capability of our Multilingual Entity Linking, MAG within AGDISTIS framework, https://github.com/dice-group/AGDISTIS. 

Once your domain synthetic datasets are created using BENGAL you can upload them in http://gerbil.aksw.org/gerbil/config. 

Maybe you already know it, but just in case. :)
