### ISSUE TITLE
Path to WordNet should be configurable

### ISSUE THREAD

**Issue by MichaelRoeder** [dice-group/BENGAL#12]
At the moment, the user has to copy the `dict` folder of WordNet into Bengal. This shouldn't be necessary. Instead, the user should be enabled to define the path to WordNet, e.g., via a CLI parameter.

**Comment by nikit-srivastava** [comment]
@MichaelRoeder since we are going to include a cli option for `dict` folder, should we do it for `en_surface_forms.tsv` as well?

**Comment by MichaelRoeder** [comment]
Yes, please :smiley:
